DROP TABLE IF EXISTS Users CASCADE;
DROP TABLE IF EXISTS League CASCADE;
DROP TABLE IF EXISTS Driver CASCADE;
DROP TABLE IF EXISTS Race CASCADE;
DROP TABLE IF EXISTS Rslt CASCADE;
DROP TABLE IF EXISTS Team CASCADE;